# pylint: skip-file

from typing import Literal

class Axis:
    def set_visible(self, visible: bool) -> None: ...
    def tick_bottom(self) -> None: ...
    def set_label_position(self, position: Literal["bottom", "top"]) -> None: ...
